apiVersion: v1
kind: Secret
metadata:
  name: go-sql-proxy
type: Opaque
data:
  SOURCE_DATABASE_SERVER: {{ .Values.settings.source.host | b64enc | quote }}
  SOURCE_DATABASE_PORT: {{ .Values.settings.source.port | b64enc | quote }}
  SOURCE_DATABASE_USER: {{ .Values.settings.source.user | b64enc | quote }}
  SOURCE_DATABASE_PASSWORD: {{ .Values.settings.source.password | b64enc | quote }}
  SOURCE_DATABASE_NAME: {{ .Values.settings.source.database | b64enc | quote }}
