apiVersion: v1
kind: Secret
metadata:
  name: go-sql-proxy
type: Opaque
data:
  SOURCE_DATABASE_SERVER: {{ .Values.settings.source.host | toString | b64enc | quote }}
  SOURCE_DATABASE_PORT: {{ .Values.settings.source.port | toString | b64enc | quote }}
  SOURCE_DATABASE_USER: {{ .Values.settings.source.user | toString | b64enc | quote }}
  SOURCE_DATABASE_PASSWORD: {{ .Values.settings.source.password | toString | b64enc | quote }}
  SOURCE_DATABASE_NAME: {{ .Values.settings.source.database | toString | b64enc | quote }}
