apiVersion: v1
kind: Service
metadata:
  name: "go-sql-proxy"
  labels:
    app: "go-sql-proxy"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: http
      protocol: TCP
      name: mysql
    - port: 9090
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    app: "go-sql-proxy"
