name: Build, Test and Publish

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker build and push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker buildx build \
          --platform linux/amd64 \
          --pull \
          --build-arg VERSION=${GITHUB_RUN_NUMBER} \
          --build-arg GIT_COMMIT=${DRONE_COMMIT_SHA} \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
          --cache-from supporttools/go-sql-proxy:latest \
          -t supporttools/go-sql-proxy:"0.2.${{ github.run_number }}" \
          -t supporttools/go-sql-proxy:latest \
          --push \
          -f Dockerfile .

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Package Helm chart
        run: |
          export CHART_VERSION="0.2.${{ github.run_number }}"
          export APP_VERSION="0.2.${{ github.run_number }}"
          echo "CHART_VERSION=${CHART_VERSION}"
          echo "APP_VERSION=${APP_VERSION}"
          envsubst < helm/go-sql-proxy/Chart.yaml.template > helm/go-sql-proxy/Chart.yaml
          envsubst < helm/go-sql-proxy/values.yaml.template > helm/go-sql-proxy/values.yaml
          helm package helm/go-sql-proxy --destination helm/repo

      - name: Checkout helm-chart repository
        uses: actions/checkout@v2
        with:
          repository: SupportTools/helm-chart
          path: helm-chart
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"

      - name: Update Helm repository
        run: |
          cp helm/repo/go-sql-proxy-*.tgz helm-chart/
          cd helm-chart
          helm repo index . --url https://charts.support.tools/
          git add .
          git commit -m "Update Helm chart for go-sql-proxy"
          git push
